//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TaskManager.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FORMVIEW_PROCESS_TAB        101
#define IDD_FORMVIEW_PROCESS_TAB_FILE   101
#define IDD_TASKMANAGER_DIALOG          102
#define ID_PROCESS                      102
#define ID_CPU_USAGE                    103
#define ID_MEMORY                       104
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDI_ICON                        130
#define IDD_DIALOG_APPLICATION          131
#define IDD_DIALOG_PROCESS              132
#define IDR_MANIFEST                    133
#define IDR_MENU_APPLICATION            135
#define IDR_MENU_APPLICATION_ONE        135
#define IDD_DIALOG_SERVER               136
#define IDD_DIALOG_COLUMN               137
#define IDR_MENU_APPLICATION_TWO        138
#define IDD_FORMVIEW_PROCESS_TAB_MODULE 138
#define IDR_MENU_SERVER                 139
#define IDR_MENU_SERVICE                139
#define IDD_FORMVIEW_PROCESS_TAB_THREAD 139
#define IDD_FORMVIEW_PROCESS_TAB_MEMORY 140
#define IDR_MENU_PROCESS                140
#define IDD_DIALOG_CPU                  141
#define IDD_FORMVIEW_PROCESS_           142
#define IDD_FORMVIEW_PROCESS_TAB_PORT   142
#define IDD_FORMVIEW_PROCESS_TAB_ENVIROMENT 143
#define IDD_FORMVIEW_PROCESS_TAB_ENVIRONMENT 143
#define IDD_FORMVIEW_PROCESS_TAB_HANDLE 144
#define IDD_DIALOG_MODULE               145
#define IDD_DIALOG_DUMP                 146
#define IDD_DIALOG_PROCESS_INFORMATION  147
#define IDR_MENU1                       148
#define IDR_MENU_PROCESS_THREAD         148
#define IDD_DIALOG_DISK_INFO            149
#define IDD_DIALOG1                     150
#define IDI_ICON1                       151
#define IDI_ICON_SERVICE                151
#define IDC_TAB                         1000
#define IDC_STATUS                      1001
#define IDC_LIST_APPLICATION            1001
#define IDC_BUTTON_CHANGE_TASK          1002
#define IDC_BUTTON_TERMINATE_TASK       1003
#define IDC_LIST_PROCESS                1003
#define IDC_BUTTON_NEW_TASK             1004
#define IDC_CHECK_PROCESS               1004
#define IDC_BUTTON_PROCESS              1005
#define IDC_LIST_SERVER                 1006
#define IDC_BUTTON_SERVER               1007
#define IDC_BUTTON_COLUMN_OK            1007
#define IDC_BUTTON_COLUMN_CANCEL        1008
#define IDC_CHECK_COLUMN_PROCEE_NAME    1009
#define IDC_CHECK_COLUMN_PROCESS_ID     1010
#define IDC_CHECK_COLUMN_CPU_USAGE      1011
#define IDC_CHECK_COLUMN_CPU_TIME       1012
#define IDC_CHECK_COLUMN_MEMORY_USAGE   1013
#define IDC_CHECK_COLUMN_MEMORY_USAGE_DELTA 1014
#define IDC_CHECK_COLUMN_MEMORY_PEAK_USAGE 1015
#define IDC_CHECK_COLUMN_PAGE_FAULTS    1016
#define IDC_CHECK_COLUMN_USER_OBJECT    1017
#define IDC_CHECK_COLUMN_IO_READ        1018
#define IDC_CHECK_COLUMN_IO_READ_BYTE   1019
#define IDC_CHECK_COLUMN_SESSION_ID     1020
#define IDC_CHECK_COLUMN_USER_NAME      1021
#define IDC_CHECK_COLUMN_PAGE_FAULTS_DELTA 1022
#define IDC_CHECK_COLUMN_VIRTUAL_MEMORY_SIZE 1023
#define IDC_CHECK_COLUMN_NON_PAGE_POOL  1024
#define IDC_CHECK_COLUMN_PAGE_POOL      1025
#define IDC_CHECK_COLUMN_BASE_PRIORITY  1026
#define IDC_CHECK_COLUMN_HANDLE_COUNT   1027
#define IDC_CHECK_COLUMN_THREAD_COUNT   1028
#define IDC_CHECK_COLUMN_GDI_OBJECT     1029
#define IDC_CHECK_COLUMN_IO_WRITE       1030
#define IDC_CHECK_COLUMN_IO_WRITE_BYTE  1031
#define IDC_CHECK_COLUMN_IO_OTHER       1032
#define IDC_CHECK_COLUMN_IO_OTHER_BYTE  1033
#define IDC_CHECK_COLUMN_IMAGE_PATH     1034
#define IDC_TAB_PROCESS                 1035
#define IDC_LIST_PROCESS_TAB            1036
#define IDC_LIST_PROCESS_TAB_FILE_INFOR 1036
#define IDC_LIST_PROCESS_TAB_FILE       1036
#define IDC_LIST_PROCESS_MODULE         1037
#define IDC_LIST_PROCESS_TAB_MODULE     1037
#define IDC_LIST_TAB_MEMORY             1038
#define IDC_LIST_PROCESS_TAB_MEMORY     1038
#define IDC_LIST_PROCESS_TAB_PORT       1038
#define IDC_LIST_PROCESS_TAB_ENV        1038
#define IDC_LIST_PROCESS_TAB_HANDLE     1038
#define IDC_LIST_MODULE                 1038
#define IDC_LIST_PROCESS_TAB_THREAD     1039
#define IDC_CHECK_CPU1                  1041
#define IDC_CHECK_CPU2                  1042
#define IDC_CHECK_CPU3                  1043
#define IDC_CHECK_CPU4                  1044
#define IDC_CHECK_CPU5                  1045
#define IDC_CHECK_CPU6                  1046
#define IDC_CHECK_CPU7                  1047
#define IDC_CHECK_CPU8                  1048
#define IDC_BUTTON_CPU_OK               1049
#define IDC_BUTTON_CPU_CANCEL           1050
#define IDC_EDIT_DUMP_TEXT              1050
#define IDC_BUTTON_DUMP_OK              1051
#define IDC_BUTTON_DUMP_CANCEL          1052
#define IDC_CHECK_DUMP1                 1053
#define IDC_CHECK_DUMP2                 1054
#define IDC_CHECK_DUMP3                 1055
#define IDC_CHECK_DUMP4                 1056
#define IDC_STATIC_SPLITTERY            1056
#define IDC_CHECK_DUMP5                 1057
#define IDC_PROGRESS_PROCESS_CPU        1057
#define IDC_CHECK_DUMP6                 1058
#define IDC_PROGRESS_PROCESS_CPU2       1058
#define IDC_PROGRESS_PROCESS_CPU_KERNEL 1058
#define IDC_CHECK_DUMP7                 1059
#define IDC_STATIC_PROCESS_CPU_MIN      1059
#define IDC_CHECK_DUMP8                 1060
#define IDC_STATIC_PROCESS_CPU_AVG      1060
#define IDC_CHECK_DUMP9                 1061
#define IDC_STATIC_PROCESS_CPU_MAX      1061
#define IDC_CHECK_DUMP10                1062
#define IDC_STATIC_PROCESS_CPU_MAX2     1062
#define IDC_STATIC_PROCESS_CPU_VAL      1062
#define IDC_CHECK_DUMP11                1063
#define IDC_STATIC_CPU                  1063
#define IDC_CHECK_DUMP12                1064
#define IDC_STATIC_MEMORY               1064
#define IDC_CHECK_DUMP13                1065
#define IDC_STATIC_IO                   1065
#define IDC_CHECK_DUMP14                1066
#define IDC_STATIC_MEMORY_GRAPH         1066
#define IDC_CHECK_DUMP15                1067
#define IDC_STATIC_MEMORY_GRAPH2        1067
#define IDC_STATIC_IO_GRAPH             1067
#define IDC_STATIC_DRIVE_MODEL_NUM      1067
#define IDC_CHECK_DUMP16                1068
#define IDC_STATIC_PROCESS_CPU_VAL_KERNEL 1068
#define IDC_STATIC_SERIAL_NUM           1068
#define IDC_CHECK_DUMP17                1069
#define IDC_STATIC_PROCESS_CPU_MIN_KERNEL 1069
#define IDC_STATIC_RIVISION_NUM         1069
#define IDC_CHECK_DUMP18                1070
#define IDC_STATIC_PROCESS_CPU_AVG_KERNEL 1070
#define IDC_STATIC_DIRVE_SIZE           1070
#define IDC_CHECK_DUMP19                1071
#define IDC_STATIC_PROCESS_CPU_MAX_KERNEL 1071
#define IDC_STATIC_CONTROL              1071
#define IDC_CHECK_DUMP20                1072
#define IDC_STATIC_BUFFER_SIZE          1072
#define IDC_CHECK_DUMP21                1073
#define IDC_STATIC_DIRVE_TYPE           1073
#define IDC_CHECK_DUMP22                1074
#define IDC_TREE1                       1074
#define IDC_TREE_DRIVE                  1074
#define IDC_CHECK_DUMP23                1075
#define IDC_STATIC_GROUP                1075
#define IDC_STATIC_DISK_GROUP1          1075
#define IDC_CHECK_DUMP24                1076
#define IDC_STATIC_SERIAL               1076
#define IDC_STATIC_REVISION             1077
#define IDC_STATIC_BUFFER               1078
#define IDC_STATIC_DRIVER               1079
#define IDC_STATIC_SIZE                 1080
#define IDC_STATIC_TYPE                 1081
#define IDC_STATIC_CHART                1082
#define IDC_STATIC_PERFORMANCE_CHART    1083
#define IDC_COMBO_SELECT_DISK_PERFORMANCE 1084
#define IDC_STATIC_FILE_SYSTEM          1085
#define IDC_STATIC_DISK_USAGE           1086
#define IDC_STATIC_DISK_FREE            1087
#define IDC_STATIC_DISK_GROUP2          1088
#define IDC_LIST_DISK                   1089
#define IDC_BUTTON_DISK_VIEW            1090
#define IDC_STATIC_DISK_PERFORMANCE     1091
#define IDC_COMBO1                      1093
#define IDC_COMBO_SERVICE_TYPE          1093
#define IDC_STATIC_SERVICE              1094
#define IDC_STATIC_SERVICE_TYPE         1094
#define IDC_STATIC_SERVICE_STATUS       1095
#define IDC_COMBO_SERVICE_TYPE2         1096
#define IDC_COMBO_SERVICE_STATUS        1096
#define ID_FILE_EXIT                    32784
#define ID_OPTION_TOP                   32785
#define ID_OPTION_MIN                   32786
#define ID_OPTION                       32787
#define ID_OPTION_HIDE                  32788
#define ID_VIEW_REFRESH                 32789
#define ID_VIEW_FLUSH                   32790
#define ID_VIEW_SPEED_HIGH              32791
#define ID_VIEW_SPEED_NORMAL            32792
#define ID_VIEW_SPEED_LOW               32793
#define ID_VIEW_SPEED_STOP              32794
#define ID_VIEW_COL                     32795
#define ID_HELP_ABOUT                   32796
#define ID_APPLICATION_CHANGE           32832
#define ID_APPLICATION_TOP              32833
#define ID_APPLICATION_MIN              32834
#define ID_APPLICATION_MAX              32835
#define ID_APPLICATION_CASCADE          32837
#define ID_APPLICATION_LANDSCAPE        32838
#define ID_APPLICATION_PORTRAIT         32839
#define ID_APPLICATION_TERMINATE        32840
#define ID_APPLICATION_TURN_PROCESS     32841
#define ID_APPLICATION_NEW_TASK         32847
#define ID_APPLICATION_LARGE            32848
#define ID_APPLICATION_SMALL            32849
#define ID_APPLICATION_DETAIL           32850
#define ID_Menu                         32851
#define ID_SERVICE_SATRT                32858
#define ID_SERVICE_STOP                 32859
#define ID_SERVICE_PAUSE                32860
#define ID_SERVICE_RESUME               32861
#define ID_SERVICE_DELETE               32862
#define ID_SERVICE_OPEN                 32863
#define ID_SERVICE_AUTO_START           32868
#define ID_SERVICE_MANUAL_START         32869
#define ID_SERVICE_DISABLED             32870
#define ID_SERVICE_MANNUAL_START        32871
#define ID_PROCESS_END                  32885
#define ID_PROCESS_END_TREE             32886
#define ID_PROCESS_DEBUG                32887
#define ID_PROCESS_REALTIME             32888
#define ID_PROCESS_HIGH                 32889
#define ID_PROCESS_ABOVE_HIGH           32890
#define ID_PROCESS_NORMAL               32891
#define ID_PROCES_BELOW_LOW             32892
#define ID_PROCESS_LOW                  32893
#define ID_PROCESS_CPU                  32894
#define ID_PROCESS_PROPERTY             32896
#define ID_PROCESS_OPEN                 32897
#define ID_PROCESS_SUSPEND              32899
#define ID_THREAD_PAUSE                 32904
#define ID_TRHEAD_SU                    32905
#define ID_THREAD_SUSPEND               32906
#define ID_THREAD_RESUME                32907
#define ID_THREAD_PRIORITY              32908
#define ID_THREAD_TERMINATE             32909
#define ID_THREAD_REALTIME              32917
#define ID_THREAD_HIGHT                 32918
#define ID_THREAD_ABOVE_NORMAL          32919
#define ID_THREAD_NORMAL                32920
#define ID_THREAD_BELOW_NORMAL          32921
#define ID_THREAD_LOW                   32922
#define ID_THREAD_IDLE                  32923
#define ID_PROCESS_VIEW                 32931
#define ID_32932                        32932
#define ID_32933                        32933
#define ID_32934                        32934
#define ID_32935                        32935
#define ID_32936                        32936
#define ID_32937                        32937
#define ID_                             32938
#define ID_SYSTEM_STANDBY               32939
#define ID_SYSTEM_HIBERANTE             32940
#define ID_SYSTEM_LOGOFF                32941
#define ID_SYSTEM_RESTART               32942
#define ID_SYSTEM_TURNOFF               32943
#define ID_SYSTEM_SWITCH                32944

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32945
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
